### ISSUE TITLE
Generate a Stylesheet with Higher Specificity Class Names

### ISSUE THREAD

**Issue by porada** [Automattic/color-studio#26]
```css
.color-white.color-white {
  color: #fff;
}

.color-black.color-black {
  color: #000;
}

.color-gray-0.color-gray-0 {
  color: #f6f7f7;
}

/* … */
```
